_wandb:
    value:
        cli_version: 0.23.0
        e:
            6me618zb704g9v1znphrbs6omrpezx1e:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43677159424"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_001
                startedAt: "2025-11-24T17:21:56.014716Z"
                writerId: 6me618zb704g9v1znphrbs6omrpezx1e
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 4.586032684038303
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 1.5263495397682354
device:
    value: cuda
dfl:
    value: 1.1602287406094018
epochs:
    value: 6
hsv_h:
    value: 0.06075448519014384
hsv_s:
    value: 0.4682096494749166
hsv_v:
    value: 0.4260206371941118
imgsz:
    value: 640
lr0:
    value: 0.0004192159350410976
lrf:
    value: 0.28242799368681437
mixup:
    value: 0.06092275383467414
momentum:
    value: 0.9442211153671616
mosaic:
    value: 0.9041986740582306
optimizer:
    value: SGD
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 1.269331322352
translate:
    value: 0.19312640661491187
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.0046450412719997725
warmup_epochs:
    value: 2
warmup_momentum:
    value: 0.766586555987919
weight_decay:
    value: 2.5081156860452307e-05
workers:
    value: 8
