_wandb:
    value:
        cli_version: 0.23.0
        e:
            tgpz6jxofv20kwgh0mgi6qibysekf2td:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43677323264"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_003
                startedAt: "2025-11-24T17:22:13.551698Z"
                writerId: tgpz6jxofv20kwgh0mgi6qibysekf2td
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 4.444267910404542
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 1.0376985928164089
device:
    value: cuda
dfl:
    value: 0.6738035892876946
epochs:
    value: 6
hsv_h:
    value: 0.07722447692966575
hsv_s:
    value: 0.479486272613669
hsv_v:
    value: 0.40220884684944097
imgsz:
    value: 640
lr0:
    value: 0.00040375061884407573
lrf:
    value: 0.2123738038749523
mixup:
    value: 0.15425406933718916
momentum:
    value: 0.9151235299789898
mosaic:
    value: 0.8645035840204937
optimizer:
    value: AdamW
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 1.1892768570729007
translate:
    value: 0.14137146876952342
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.09868869366005173
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.5335477896558969
weight_decay:
    value: 1.913588048769229e-05
workers:
    value: 8
