_wandb:
    value:
        cli_version: 0.23.0
        e:
            4fqawo4wunv58c9ax0513ac676zk93xn:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43604176896"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-b1dd15af-aea8-a3b9-f66f-364e15125b09
                host: e45ea6fd2b71
                memory:
                    total: "13605851136"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_143454/trial_000
                startedAt: "2025-11-24T15:52:15.139815Z"
                writerId: 4fqawo4wunv58c9ax0513ac676zk93xn
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: bdd100k_yolo_limited
iou_threshold:
    value: 0.5
model:
    value: yolov10n_finetuned_20251124
split:
    value: test
