_wandb:
    value:
        cli_version: 0.23.0
        e:
            narykxc3xwuxu69vzrg4r1lngxwklja9:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43512066048"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-b1dd15af-aea8-a3b9-f66f-364e15125b09
                host: e45ea6fd2b71
                memory:
                    total: "13605851136"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_143454/trial_004
                startedAt: "2025-11-24T14:42:07.514552Z"
                writerId: narykxc3xwuxu69vzrg4r1lngxwklja9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 5.921772081247226
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 0.6647956588012092
device:
    value: cuda
dfl:
    value: 0.9035129187295441
epochs:
    value: 2
hsv_h:
    value: 0.0720370628774468
hsv_s:
    value: 0.6842948633963384
hsv_v:
    value: 0.7564390595178256
imgsz:
    value: 640
lr0:
    value: 0.0020744284653995706
lrf:
    value: 0.11287713143501954
mixup:
    value: 0.11637518504059235
momentum:
    value: 0.8685852176760903
mosaic:
    value: 0.5434672040667519
optimizer:
    value: Adam
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 0.7985317885511489
translate:
    value: 0.054878229360876045
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.07810484888161186
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.5890418554419901
weight_decay:
    value: 0.00010094377952377089
workers:
    value: 8
