_wandb:
    value:
        cli_version: 0.23.0
        e:
            hu9ncjdndbki8vhc7ioujdtph5g1lk0n:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43677405184"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_004
                startedAt: "2025-11-24T17:22:22.218389Z"
                writerId: hu9ncjdndbki8vhc7ioujdtph5g1lk0n
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 6.565246110151298
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 0.5381286901161428
device:
    value: cuda
dfl:
    value: 0.6618371404899567
epochs:
    value: 6
hsv_h:
    value: 0.01195942459383017
hsv_s:
    value: 0.685297914889198
hsv_v:
    value: 0.704314019446759
imgsz:
    value: 640
lr0:
    value: 0.00012822825454807568
lrf:
    value: 0.2243929286862649
mixup:
    value: 0.10454656587639882
momentum:
    value: 0.8890219986432096
mosaic:
    value: 0.7468977981821954
optimizer:
    value: SGD
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 1.0367663185416978
translate:
    value: 0.1541934359909122
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.04722149251619493
warmup_epochs:
    value: 2
warmup_momentum:
    value: 0.8992457341593469
weight_decay:
    value: 0.0002878805718308924
workers:
    value: 8
