_wandb:
    value:
        cli_version: 0.23.0
        e:
            tq6blzi3ta5sl30ac27jbx5umuygv2xy:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43677241344"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_002
                startedAt: "2025-11-24T17:22:05.004913Z"
                writerId: tq6blzi3ta5sl30ac27jbx5umuygv2xy
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 5.175897174514871
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 0.5678409333658071
device:
    value: cuda
dfl:
    value: 0.9879954961448965
epochs:
    value: 6
hsv_h:
    value: 0.09695846277645587
hsv_s:
    value: 0.7100531293444459
hsv_v:
    value: 0.7757995766256757
imgsz:
    value: 640
lr0:
    value: 0.0035067764992972213
lrf:
    value: 0.20351199264000677
mixup:
    value: 0.0176985004103839
momentum:
    value: 0.9295026741224778
mosaic:
    value: 0.9609371175115584
optimizer:
    value: Adam
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 1.2368964102565894
translate:
    value: 0.11957999576221703
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.018485445552552705
warmup_epochs:
    value: 2
warmup_momentum:
    value: 0.7460196257044758
weight_decay:
    value: 4.201672054372529e-05
workers:
    value: 8
