_wandb:
    value:
        cli_version: 0.23.0
        e:
            1lm917uegwibocyzrwp0eqsx483g7ad6:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43677487104"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_005
                startedAt: "2025-11-24T17:22:30.829293Z"
                writerId: 1lm917uegwibocyzrwp0eqsx483g7ad6
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 7.527204344867594
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 1.0279501437896141
device:
    value: cuda
dfl:
    value: 0.8615505272015526
epochs:
    value: 6
hsv_h:
    value: 0.04538736473066358
hsv_s:
    value: 0.7836061767103539
hsv_v:
    value: 0.7158648475327121
imgsz:
    value: 640
lr0:
    value: 0.0029743624956974353
lrf:
    value: 0.12274407820497062
mixup:
    value: 0.06479705467491233
momentum:
    value: 0.9129815296507543
mosaic:
    value: 0.5408996429549441
optimizer:
    value: Adam
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 0.7642451988389807
translate:
    value: 0.021879670536597215
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.09639705131844271
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.7976654119539656
weight_decay:
    value: 5.692203314794969e-05
workers:
    value: 8
