_wandb:
    value:
        cli_version: 0.23.0
        e:
            ku6dcut67znv0zmxwe2d620a7a6p7d0i:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43706343424"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_007
                startedAt: "2025-11-24T17:28:03.038249Z"
                writerId: ku6dcut67znv0zmxwe2d620a7a6p7d0i
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 6.613713053144144
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 1.1112028737029582
device:
    value: cuda
dfl:
    value: 1.9042471219221202
epochs:
    value: 6
hsv_h:
    value: 0.03514104336036132
hsv_s:
    value: 0.7318731252142745
hsv_v:
    value: 0.7700320083871631
imgsz:
    value: 640
lr0:
    value: 0.0019165268411797845
lrf:
    value: 0.21534167280871647
mixup:
    value: 0.11312539580047143
momentum:
    value: 0.8879822625378682
mosaic:
    value: 0.5993021732090446
optimizer:
    value: Adam
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 0.8082871615312168
translate:
    value: 0.05846935870915645
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.028087658811627066
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.6555294354143696
weight_decay:
    value: 2.2760157668181607e-05
workers:
    value: 8
