_wandb:
    value:
        cli_version: 0.23.0
        e:
            f3d4k6jvb65wfywsvbmgbgqvvgjtarhk:
                codePath: yolo_v8_tuning_training.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/m3mahdy/computer_vision_yolo/blob/main/tune_train/yolo_v8_tuning_training.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "43720962048"
                email: m3edris@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c35ed661-5eba-0cbe-4bef-2d69306a572e
                host: dde76a1a5076
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: yolo_v8_tuning_training.ipynb
                python: CPython 3.12.12
                root: /computer_vision_yolo/tune_train/tune/yolov10n_tune_20251124_171817/trial_008
                startedAt: "2025-11-24T17:30:54.948214Z"
                writerId: f3d4k6jvb65wfywsvbmgbgqvvgjtarhk
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
batch:
    value: 64
box:
    value: 4.386664771990909
cache:
    value: true
close_mosaic:
    value: 10
cls:
    value: 1.3583091175537416
device:
    value: cuda
dfl:
    value: 0.5083135696883885
epochs:
    value: 6
hsv_h:
    value: 0.0250091602148839
hsv_s:
    value: 0.728505769225322
hsv_v:
    value: 0.5957830278763969
imgsz:
    value: 640
lr0:
    value: 0.0010423691526912312
lrf:
    value: 0.18230066528566263
mixup:
    value: 0.07943917534957151
momentum:
    value: 0.8711610558339428
mosaic:
    value: 0.5937494164126712
optimizer:
    value: SGD
patience:
    value: 20
plots:
    value: true
save:
    value: true
scale:
    value: 0.9113158787789211
translate:
    value: 0.013084903958918377
val:
    value: true
verbose:
    value: true
warmup_bias_lr:
    value: 0.045376403322176954
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.5846111091001842
weight_decay:
    value: 2.3347006815835546e-05
workers:
    value: 8
